# Generated by Django 5.2.17 on 2026-09-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_activity_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
