# Generated by Django 6.1.1 on 2026-09-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_skill_level_experience_order_alter_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
