# Generated by Django 6.1.1 on 2026-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_id_alter_projectimage_id_and_more'),
        ('users', '0007_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/'),
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('issued_by', models.CharField(blank=True, max_length=500, null=True)),
                ('what_learnt', models.CharField(max_length=3000)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('photo_overview', models.ImageField(blank=True, null=True, upload_to='certificate_overviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technologies', models.ManyToManyField(related_name='cert_technologies', to='projects.technology')),
            ],
        ),
    ]
