# Generated by Django 6.1.1 on 2026-09-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_id_alter_projectimage_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
